baseURL: "https://feinberg-lab.github.io/"

# These must be FALSE to stop the doubling
canonifyURLs: false
relativeURLs: false

title: "Feinberg Lab"

# This ensures Hugo knows exactly where the 'root' is
# (it helps images find the /images/ folder)
uglyURLs: false

markup:
  goldmark:
    renderer:
      unsafe: true # This allows <div> and <span> tags in your content 
      
taxonomies:
  tag: tags
  category: categories
  author: authors  # <--- This MUST be here
      
security:
  funcs:
    getenv:
      - '^HUGO_'
      - '^CI$'
      - '^WC_POST_CSS$'  # This is the line that fixes the error
