baseURL: "https://smhakkinen.github.io/website_skeleton/"

# These must be FALSE to stop the doubling
canonifyURLs: false
relativeURLs: false

# This ensures Hugo knows exactly where the 'root' is
# (it helps images find the /images/ folder)
uglyURLs: false

markup:
  goldmark:
    renderer:
      unsafe: true # This allows <div> and <span> tags in your content
      
security:
  funcs:
    getenv:
      - '^HUGO_'
      - '^CI$'
      - '^WC_POST_CSS$'  # This is the line that fixes the error